Failure # 1 (occurred at 2023-01-21_08-52-28)
[36mray::ImplicitFunc.train()[39m (pid=8694, ip=10.0.0.18, repr=train)
  File "/home/azureuser/.cache/pypoetry/virtualenvs/tentamen-OYVjJm_Y-py3.9/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 367, in train
    raise skipped from exception_cause(skipped)
  File "/home/azureuser/.cache/pypoetry/virtualenvs/tentamen-OYVjJm_Y-py3.9/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 335, in entrypoint
    return self._trainable_func(
  File "/home/azureuser/.cache/pypoetry/virtualenvs/tentamen-OYVjJm_Y-py3.9/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 652, in _trainable_func
    output = fn()
  File "/home/azureuser/code/tentamen/dev/scripts/02_tune.py", line 88, in train
    model = GRUmodel(config)  # type: ignore
NameError: name 'GRUmodel' is not defined
